name: Verify build 

on: push

jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      
      - name: Cache Node.js dependencies
        id: node-cache
        uses: actions/cache@v2
        with:
            path: node_modules
            key: node-modules-&{{ hashFiles('package-lock.json') }}

      - name: Install Node.js dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: yarn
      
      - name: Build project
        run: yarn build
    
  run-linters:
    name: Lint
    needs: build-project
    runs-on: ubuntu-latest
      
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
        
      - name: Cache Node.js dependencies
        id: node-cache
        uses: actions/cache@v2
        with:
            path: node_modules
            key: node-modules-&{{ hashFiles('package-lock.json') }}

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          eslint: true
          prettier: true
